POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
  "name": "New Product",
  "price": 100
}

###

GET http://localhost:8000/products/fe713a52-ae56-4b86-92b6-7784841d8ec0 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8000/products/fe713a52-ae56-4b86-92b6-7784841d8ec0 HTTP/1.1
Content-Type: application/json

{
  "name": "Product Updated",
  "price": 200
}